# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#'
#' K-prime distribution
#'
#' @description
#'
#' Distribution, quantile and random variates of the k-prime distribution.
#'
#' @details
#'
#' Suppose \eqn{y \sim \chi^2\left(\nu_1\right)}{y ~ x^2(v1)}, and
#' \eqn{x \sim t \left(\nu_2, a\sqrt{y/\nu_1}/b\right)}{x ~ t(v2,(a/b) sqrt(y/v1))}.
#' Then the random variable
#' \deqn{T = b x}{T = b x}
#' takes a K prime distribution with parameters 
#' \eqn{\nu_1, \nu_2, a, b}{v1, v2, a, b}. In Lecoutre's terminology,
#' \eqn{T \sim K'_{\nu_1, \nu_2}\left(a, b\right)}{T ~ K'_v1,v2(a,b)}
#'
#' Equivalently, we can think of
#' \deqn{T = \frac{b Z + a \sqrt{\chi^2_{\nu_1} / \nu_1}}{\sqrt{\chi^2_{\nu_2} / \nu_2}}}{T = (bZ + a sqrt(chi2_v1/v1)) / sqrt(chi2_v2/v2)}
#' where \eqn{Z} is a standard normal, and the normal and the (central) chi-squares are
#' independent of each other. When \eqn{a=0}{a=0} we recover
#' a central t distribution; 
#' when \eqn{\nu_1=\infty}{v1=inf} we recover a rescaled non-central t distribution;
#' when \eqn{b=0}{b=0}, we get a rescaled square root of a central F
#' distribution; when \eqn{\nu_2=\infty}{v2=inf}, we recover a 
#' Lambda prime distribution.
#'
#' @references
#'
#' Poitevineau, J., and Lecoutre, B. "Implementing Bayesian predictive procedures: The K-prime and K-square distributions." 
#' Computational Statistics & Data Analysis 54, no. 3 (2010): 724-731.
#' \url{https://arxiv.org/abs/1003.4890}
#'
#' @param q vector of quantiles.
#' @param p vector of probabilities.
#' @param n number of observations. 
#' @param v1 the degrees of freedom in the numerator chisquare. When
#' (positive) infinite, we recover a non-central t 
#' distribution with \code{v2} degrees of freedom and non-centrality
#' parameter \code{a}, scaled by \code{b}.
#' This will be recycled against the \code{q,p,n}.
#' @param v2 the degrees of freedom in the denominator chisquare.
#' When equal to infinity, we recover the Lambda prime distribution.
#' This will be recycled against the \code{q,p,n}.
#' @param a the non-centrality scaling parameter. When equal to zero,
#' we recover the (central) t distribution.
#' This will be recycled against the \code{q,p,n}.
#' @param b the scaling parameter.
#' This will be recycled against the \code{q,p,n}.
#' @param lower_tail  boolean of whether to compute the lower tail of the
#' CDF or quantile.
#'
#' @return \code{pkprime} gives the 
#' distribution function, \code{qkprime} gives the quantile function, 
#' and \code{rkprime} generates random deviates.
#'
#' Invalid arguments will result in return value \code{NaN} with a warning.
#'
#' @template etc
#' @name kprime 
#' @rdname kprime 
#' @export
pkprime <- function(q, v1, v2, a, b, lower_tail = TRUE) {
    .Call('_kprime_pkprime', PACKAGE = 'kprime', q, v1, v2, a, b, lower_tail)
}

